/**
 * @fileoverview Script to generate precomputed embedding vectors for all 120 persona patterns.
 * 
 * Embeddings are calculated using Gemini Embedding API (gemini-embedding-2, 768 dimensions)
 * with strict rate-limit protection (700ms throttle + 30s retry on 429).
 * 
 * Usage:
 *   npm run generate:persona-vectors --workspace=bot-backend
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { personaPatterns, PersonaPattern } from '@rebecca/persona';
import * as gemini from '../src/services/gemini';

interface PersonaPatternWithVector extends PersonaPattern {
  vector: number[];
}

async function generateAll() {
  console.log(`=======================================================`);
  console.log(` 🔮 Precomputing Embedding Vectors for ${personaPatterns.length} Persona Patterns`);
  console.log(`=======================================================\n`);

  const results: PersonaPatternWithVector[] = [];

  for (let i = 0; i < personaPatterns.length; i++) {
    const pattern = personaPatterns[i];
    console.log(`[${i + 1}/${personaPatterns.length}] Embedding #${pattern.id}: [${pattern.category}]...`);
    
    try {
      const vector = await gemini.generateEmbedding(pattern.trigger);
      if (vector && vector.length > 0) {
        results.push({
          ...pattern,
          vector,
        });
      } else {
        console.warn(`⚠️ Empty embedding received for pattern #${pattern.id}`);
      }
    } catch (err: unknown) {
      const errorObj = err as { message?: string; status?: number };
      console.error(`❌ Error on pattern #${pattern.id}:`, errorObj.message);
      if (errorObj.message?.includes('429') || errorObj.status === 429) {
        console.log('⏳ Rate limit hit. Waiting 30 seconds before retrying...');
        await new Promise((r) => setTimeout(r, 30000));
        i--; // Retry this pattern
        continue;
      }
    }

    // Throttle requests to safely respect Gemini Free Tier 100 req/min limit
    await new Promise((r) => setTimeout(r, 700));
  }

  console.log(`\n✅ Successfully generated vectors for ${results.length} patterns.`);

  const outputPath = path.resolve(__dirname, '../../../packages/persona/src/personaPatternVectors.ts');
  const fileContent = `/**
 * @fileoverview Precomputed 768-dimensional embedding vectors for the 120 Rebecca persona patterns.
 * 
 * Bundling precomputed vectors directly eliminates runtime embedding API calls,
 * avoids rate-limit (429) errors, and reduces pattern matching latency to 0.001ms.
 * 
 * Auto-generated by: apps/bot-backend/scripts/generatePersonaVectors.ts
 */

import { PersonaPattern } from './index';

export interface PersonaPatternWithVector extends PersonaPattern {
  vector: number[];
}

export const precomputedPersonaPatternEmbeddings: PersonaPatternWithVector[] = ${JSON.stringify(results, null, 2)};
`;

  fs.writeFileSync(outputPath, fileContent, 'utf-8');
  console.log(`📁 Saved precomputed dataset to: ${outputPath}\n`);
}

generateAll().catch((err) => {
  console.error('Fatal error generating persona vectors:', err);
  process.exit(1);
});
