import { AppDependencies } from '../../../src/types';

export const createMockDeps = (): AppDependencies => {
    return {
        firestore: {
            getLastMentionId: jest.fn(),
            setLastMentionId: jest.fn(),
            getUserDoc: jest.fn(),
            updateUserDoc: jest.fn(),
            getExtendedPrompt: jest.fn(),
            getTimelineSummary: jest.fn(),
            findRagMemories: jest.fn(),
            saveRagMemory: jest.fn(),
            saveRawConversationLog: jest.fn(),
            checkAndConsumeRateLimit: jest.fn(),
            hasProcessedMention: jest.fn(),
            markMentionProcessed: jest.fn(),
            appendEpisodicBuffer: jest.fn(),
            updateCoreProfile: jest.fn(),
            getAllUsers: jest.fn(),
            getRecentTimelinePosts: jest.fn(),
            saveTimelineSummary: jest.fn(),
            getRecentConversationLogs: jest.fn(),
            saveExtendedPrompt: jest.fn(),
            hasProcessedFollower: jest.fn(),
            markFollowerProcessed: jest.fn(),
            getFailedFollowers: jest.fn().mockResolvedValue([]),
            updateFollowerListStatus: jest.fn().mockResolvedValue(undefined),
            getProcessedFollowersCount: jest.fn().mockResolvedValue(0),
            updateTotalFollowers: jest.fn().mockResolvedValue(undefined),
            getLastListInteraction: jest.fn(),
            updateLastListInteraction: jest.fn(),
            getListMembersFromCache: jest.fn().mockResolvedValue([]),
            findImageByVector: jest.fn(),
            updateImageLastUsed: jest.fn(),
            saveTimelinePost: jest.fn(),
            getRecentNewsEmbeddings: jest.fn().mockResolvedValue([]),
            getAssetsPendingEmbedding: jest.fn().mockResolvedValue([]),
            updateAssetEmbedding: jest.fn().mockResolvedValue(undefined),
        } as any,
        gemini: {
            analyzeUserProfile: jest.fn(),
            analyzeImageCaption: jest.fn(),
            generateSearchQuery: jest.fn(),
            generateEmbedding: jest.fn().mockResolvedValue(new Array(768).fill(0.1)),
            detectLanguage: jest.fn().mockResolvedValue('ja'),
            generateStructuredReply: jest.fn().mockResolvedValue({ thought: '内省モック', reply: 'Mock response' }),
            verifyImageRelevance: jest.fn().mockResolvedValue(true),
            generateDreaming: jest.fn(),
            generateTimelineSummary: jest.fn(),
            generateEvolutionPrompt: jest.fn(),
            auditEvolutionPrompt: jest.fn(),
            generateStructuredNewsPost: jest.fn(),
            generateStructuredSoliloquyPost: jest.fn(),
            inferImageSearchQuery: jest.fn(),
        } as any,
        xApi: {
            getMentions: jest.fn(),
            getUserProfile: jest.fn(),
            getTweetDetails: jest.fn(),
            replyToMention: jest.fn(),
            getFollowers: jest.fn(),
            addListMember: jest.fn(),
            getUserTweets: jest.fn(),
            tweet: jest.fn(),
            uploadMedia: jest.fn(),
            cachedNumericMyUserId: 'my_id',
        } as any,
        tasks: {
            enqueueReplyTask: jest.fn(),
        } as any,
        storage: {
            downloadImage: jest.fn(),
        } as any,
        newsFetcher: {
            fetchYahooNewsHeadlines: jest.fn(),
        } as any,
    };
};
