import { AppDependencies } from '../../../src/types';

export const createMockDeps = (): AppDependencies => {
    return {
        firestore: {
            getLastMentionId: jest.fn(),
            setLastMentionId: jest.fn(),
            getUserDoc: jest.fn(),
            getExtendedPrompt: jest.fn(),
            getTimelineSummary: jest.fn(),
            findRagMemories: jest.fn(),
            saveRagMemory: jest.fn(),
            saveRawConversationLog: jest.fn(),
            checkAndConsumeRateLimit: jest.fn(),
            hasProcessedMention: jest.fn(),
            markMentionProcessed: jest.fn(),
            appendEpisodicBuffer: jest.fn(),
            updateCoreProfile: jest.fn(),
            getAllUsers: jest.fn(),
            getRecentTimelinePosts: jest.fn(),
            saveTimelineSummary: jest.fn(),
            getRecentConversationLogs: jest.fn(),
            saveExtendedPrompt: jest.fn(),
            hasProcessedFollower: jest.fn(),
            markFollowerProcessed: jest.fn(),
            getLastListInteraction: jest.fn(),
            updateLastListInteraction: jest.fn(),
            findImageByVector: jest.fn(),
            updateImageLastUsed: jest.fn(),
            saveTimelinePost: jest.fn(),
        } as any,
        gemini: {
            analyzeUserProfile: jest.fn(),
            analyzeImageCaption: jest.fn(),
            generateSearchQuery: jest.fn(),
            generateEmbedding: jest.fn(),
            detectLanguage: jest.fn(),
            generateReply: jest.fn(),
            generateDreaming: jest.fn(),
            generateTimelineSummary: jest.fn(),
            generateEvolutionPrompt: jest.fn(),
            auditEvolutionPrompt: jest.fn(),
            generateNewsPost: jest.fn(),
            inferImageSearchQuery: jest.fn(),
        } as any,
        xApi: {
            getMentions: jest.fn(),
            getUserProfile: jest.fn(),
            getTweetDetails: jest.fn(),
            replyToMention: jest.fn(),
            getFollowers: jest.fn(),
            addListMember: jest.fn(),
            getListMembers: jest.fn(),
            getUserTweets: jest.fn(),
            tweet: jest.fn(),
            uploadMedia: jest.fn(),
            cachedNumericMyUserId: 'my_id',
        } as any,
        tasks: {
            enqueueReplyTask: jest.fn(),
        } as any,
        storage: {
            downloadImage: jest.fn(),
        } as any,
        newsFetcher: {
            fetchYahooNewsHeadlines: jest.fn(),
        } as any,
    };
};
